#Define Project
substitutions:
  name: apollo-air-1
  version:  "23.11.10.1"
  device_description: ${name} made by Apollo Automation - version ${version}.
  
esphome:
  name: "${name}"
  friendly_name: Apollo AIR-1
  comment: Apollo AIR-1
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio

  on_boot:
  - priority: 900.0
    then:
      - lambda: |-
          id(cpu_speed) = ESP.getCpuFreqMHz();

  project:
    name: "ApolloAutomation.AIR-1"
    version: "${version}"

  min_version: 2023.8.1

# Define Board
esp32:
  #board: featheresp32-s2
  board: esp32-c3-devkitm-1
  framework:
    type: arduino
  
dashboard_import:
  package_import_url: github://ApolloAutomation/AIR-1/Integrations/ESPHome/AIR-1.yaml
  import_full_config: false


globals:
  - id: cpu_speed
    type: int
    restore_value: no
    initial_value: "0"

# Enable Home Assistant API
# Also Add Buzzer Service Connection
api:
  services:
    #Co2 Calibration Service
    - service: calibrate_co2_value
      variables:
        co2_ppm: float
      then:
        - scd4x.perform_forced_calibration:
            value: !lambda 'return co2_ppm;'
            id: scd40


logger:
  level: none

ota:
  password: "apolloautomation"
  safe_mode: false

wifi:

  power_save_mode: LIGHT
  output_power: 10dB

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Apollo AIR1 Hotspot"

captive_portal:

improv_serial:

web_server:
  port: 80



# Set Up Key Ports For Communication
i2c:
  sda: GPIO1
  scl: GPIO0
  id: bus_a


# Numbers For Configuration
number:
  - platform: template
    name: Co2 Calibration Number
    id: co2_calibration_number
    restore_value: true
    initial_value: 419.0
    min_value: 0.0
    max_value: 1000.0
    entity_category: "CONFIG"
    unit_of_measurement: "ppm"
    optimistic: true
    mode: box
    update_interval: never
    step: 10
    set_action:
      - scd4x.perform_forced_calibration:
          value: !lambda 'return id(co2_calibration_number).state;'
          id: scd40

  

binary_sensor:
  - platform: status
    name: Online
    id: ink_ha_connected
  

sensor:
  - platform: template
    name: "ESP Cpu Speed"
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

  - platform: template
    id: sys_esp_temperature
    name: ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 60s


  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 60s

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: "kB"
    state_class: measurement
    entity_category: "diagnostic"

  - platform: wifi_signal
    name: RSSI
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: scd4x
    id: scd40
    co2:
      name: "CO2"
      id: "co2"
    automatic_self_calibration: false
    update_interval: 60s
    measurement_mode: "periodic"
    i2c_id: bus_a
    ambient_pressure_compensation_source: dps310pressure

  - platform: dps310
    pressure:
      name: "DPS310 Pressure"
      id: dps310pressure
    update_interval: 30s
    i2c_id: bus_a

  - platform: sen5x
    id: sen55
    pm_1_0:
      name: "PM <1µm Weight concentration"
      id: pm_1_0
      accuracy_decimals: 1
    pm_2_5:
      name: "PM <2.5µm Weight concentration"
      id: pm_2_5
      accuracy_decimals: 1
    pm_4_0:
      name: "PM <4µm Weight concentration"
      id: pm_4_0
      accuracy_decimals: 1
    pm_10_0:
      name: "PM <10µm Weight concentration"
      id: pm_10_0
      accuracy_decimals: 1
    temperature:
      name: "SEN55 Temperature"
      accuracy_decimals: 1
    humidity:
      name: "SEN55 Humidity"
      accuracy_decimals: 0
    voc:
      name: "SEN55 VOC"
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    nox:
      name: "SEN55 NOX"
    acceleration_mode: low
    store_baseline: true
    address: 0x69
    update_interval: 10s

  - platform: mics_4514
    nitrogen_dioxide:
      name: Nitrogen Dioxide
    carbon_monoxide:
      name: Carbon Monoxide
    hydrogen:
      name: Hydrogen
    ethanol:
      name: Ethanol
    methane:
      name: Methane
    ammonia:
      name: Ammonia
    update_interval: 60s

  
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2812x
    pin: GPIO3
    num_leds: 2
    name: "RGB Light"
    method:
      type: esp32_rmt
      channel: 0



time:
  - platform: sntp
    id: time_sntp

button:
  - platform: restart
    icon: mdi:power-cycle
    name: "ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: "Factory Reset ESP"
    id: factory_reset_all



